# Use the official PostgreSQL image version 9.4 as base image
FROM postgres:9.4

# Set the directory for data persistence
ENV PGDATA /var/lib/postgresql/data

# Set environment variables for PostgreSQL user and password
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
